### ISSUE TITLE
fix: tour API 공통 정보 에러 수정

### ISSUE THREAD

**Issue by JONG-KYEONG** [2024-TourismContest/Yaguhang_BE#163]
## 💥이슈 설명

tour API 공통 정보 에러 수정

## 📚할 일 목록
- [ ] tour API 공통 정보 에러 수정

**Comment by JONG-KYEONG** [comment]
에러가 없었습니다.

**Comment by 5622lsk** [comment]
ㅋㅌㅊㅋㅊㅋㅌㅋㅋㅌㅋㅌㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
